# Generated by Django 3.0.5 on 2020-04-25 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('card', models.CharField(max_length=300)),
                ('cvv', models.IntegerField(default=123)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('deadline', models.TimeField(default=datetime.datetime(2020, 4, 25, 11, 41, 36, 341961))),
                ('subscripbers', models.IntegerField(default=300)),
                ('value', models.IntegerField(default=300)),
                ('cost', models.IntegerField(default=300)),
                ('discription', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.User')),
            ],
        ),
    ]
