# Generated by Django 3.0.5 on 2020-04-25 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sale',
            name='deadline',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 18, 21, 53, 637827)),
        ),
    ]
