# Generated by Django 3.0.5 on 2020-04-25 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200425_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='subscripbers',
            new_name='subscribers',
        ),
        migrations.AlterField(
            model_name='sale',
            name='deadline',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 18, 24, 26, 327912)),
        ),
    ]
