# Generated by Django 3.0.5 on 2020-04-26 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200425_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='deadline',
            field=models.TimeField(default=datetime.datetime(2020, 4, 26, 12, 20, 51, 363716)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.IntegerField(),
        ),
    ]
