# Generated by Django 3.0.5 on 2020-04-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200426_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='deadline',
            field=models.IntegerField(default=7),
        ),
    ]
